---
name: Amplication Bug report
description: Problems and issues with code of Amplication
labels: ["type/bug"]
body:
  - type: markdown
    attributes:
      value: "
        <img src='https://amplication.com/assets/amplication-logo.svg' viewBox='0 0 60 55' align='left' width='80' height='80'>
        Thank you for finding the time to report the problem!

        We really appreciate the community efforts to improve Amplication.

        Note, that you do not need to create an issue if you have a change ready to submit!

        You can open [Pull Request](https://github.com/amplication/amplication/pulls) immediately instead.
        <br clear='left'/>"
  - type: dropdown
    attributes:
      label: Amplication version
      description: >
        What Amplication version are you using? Only Amplication 0.10 is supported for bugs. If you wish to
        discuss older versions, open [Discussion](https://github.com/apache/amplication/discussions) instead!
      multiple: false
      options:
        - "0.10.3 (latest released)"
        - "0.10.2"
        - "0.10.1"
        - "0.9.0"
        - "master (development)"
    validations:
      required: true
  - type: input
    attributes:
      label: Operating System
      description: What Operating System are you using?
      placeholder: "You can get it via `cat /etc/os-release` for example"
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Deployment
      description: >
        What kind of deployment do you have? 
      multiple: false
      options:
        - "Official Amplication Helm Chart"
        - "Other 3rd-party Helm chart"
        - "Docker-Compose"
        - "Other Docker-based deployment"
        - "Virtualenv installation"
        - "Other"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Deployment details
      description: Additional description of your deployment.
      placeholder: >
        Enter any relevant details of your deployment. Especially version of your tools,
        software (docker-compose, helm, k8s, etc.), any customisation and configuration you added.
  - type: textarea
    attributes:
      label: What happened
      description: Describe what happened.
      placeholder: >
        Please provide the context in which the problem occurred and explain what happened
  - type: textarea
    attributes:
      label: What you expected to happen
      description: What do you think went wrong?
      placeholder: >
        Please explain why you think the behaviour is erroneous. It is extremely helpful if you copy&paste
        the fragment of logs showing the exact error messages or wrong behaviour and screenshots for
        UI problems or YouTube link to a video of you demonstrating the problem. You can include files by
        dragging and dropping them here.
  - type: textarea
    attributes:
      label: How to reproduce
      description: >
        What should we do to reproduce the problem? If you are not able to provide a reproducible case,
        please open a [Discussion](https://github.com/apache/amplication/discussions) instead.
      placeholder: >
        Please make sure you provide a reproducible step-by-step case of how to reproduce the problem
        as minimally and precisely as possible. Keep in mind we do not have access to your cluster or DAGs.
        Remember that non-reproducible issues will be closed! Opening a discussion is recommended as a
        first step.
  - type: textarea
    attributes:
      label: Anything else
      description: Anything else we need to know?
      placeholder: >
        How often does this problem occur? (Once? Every time? Only when certain conditions are met?)
        Any relevant logs to include? Put them here inside fenced
        ``` ``` blocks or inside a foldable details tag if it's long:
        <details><summary>x.log</summary> lots of stuff </details>
  - type: checkboxes
    attributes:
      label: Are you willing to submit PR?
      description: >
        This is absolutely not required, but we are happy to guide you in the contribution process
        especially if you already have a good understanding of how to implement the fix.
        Amplication is a community-managed project and we love to bring new contributors in.
        Find us in #how-to-pr on [Discord](https://discord.gg/cEcS9zDA)!
      options:
        - label: Yes I am willing to submit a PR!
  - type: checkboxes
    attributes:
      label: Code of Conduct
      description: The Code of Conduct helps create a safe space for everyone. We require
        that everyone agrees to it.
      options:
        - label: >
            I agree to follow this project's
            [Code of Conduct](https://github.com/amplication/amplication/blob/master/code_of_conduct.md)
          required: true
  - type: markdown
    attributes:
      value: "Thanks for completing our form!"





