# remove this comment to unbreak the file validation so it will appear in the template list when creating a new issue (for the conference day only) 
name: 🍀 Node.TLV Challenge 🍀
description: "Share with us your best idea, for anything that can make backend developers' life easier, better, faster - for a chance to win a MacBook Pro

1. Create a feature request in our project repo on GitHub with your idea. Use the QR code to navigate to the special "node.TLV challenge" 
    
    ![qr-code.png](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/2337e5c5-f93c-4c41-90db-5f2a38a5956b/qr-code.png)
    
2. Come visit us at our booth to approve your submission and pick up the coolest "open-source" t-shirt.
3. Share the idea with your colleagues and friends. 

The list of ideas will be shared with Amplication's community on Discord and Twitter and displayed in our booth. Anyone can vote for the best idea. 

The best idea with the most upvotes will win a MacBook Pro.

The challenge ends at 15:45, and the winner will get the MacBook Pro at the last coffee break between 15:45 and 16:00."
title: "🐥 Node.TLV Challenge: "
labels: [Node-TLV]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out our feature request form 🙏
  - type: textarea
    id: feature-description
    validations:
      required: true
    attributes:
      label: "🔖 Feature description"
      description: "A clear and concise description of what the feature is."
      placeholder: "You should add ..."
  - type: textarea
    id: pitch
    validations:
      required: true
    attributes:
      label: "🎤 Pitch"
      description: "Please explain why this feature should be implemented and how it would be used. Add examples, if applicable."
      placeholder: "In my use-case, ..."
  - type: textarea
    id: solution
    validations:
      required: true
    attributes:
      label: "✌️ Solution"
      description: "A clear and concise description of what you want to happen."
      placeholder: "I want this feature to, ..."
  - type: textarea
    id: alternative
    validations:
      required: true
    attributes:
      label: "🔄️ Alternative"
      description: "A clear and concise description of any alternative solutions or features you've considered."
      placeholder: "I tried, ..."
  - type: checkboxes
    id: no-duplicate-issues
    attributes:
      label: "👀 Have you spent some time to check if this issue has been raised before?"
      description: "Have you Googled for a similar issue or checked our older issues for a similar bug?"
      options:
        - label: "I checked and didn't find similar issue"
          required: true
  - type: checkboxes
    id: read-code-of-conduct
    attributes:
      label: "🏢 Have you read the Code of Conduct?"
      options:
        - label: "I have read the [Code of Conduct](https://github.com/amplication/amplication/blob/master/code_of_conduct.md)"
          required: true
