name: Package Size Report

on:
  pull_request:

jobs:
  pkg-size-report:
    name: Package Size Report
    runs-on: ubuntu-20.04  

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Package size report
        uses: pkg-size/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          build-command: "npx lerna bootstrap -- --production" # ⬅ Set a different build script here
