name: Run Docker Build

on:
  workflow_dispatch:

jobs:
  run-build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t amplication .
      - run: docker run -d --name amplication_1 amplication
      - run: docker logs amplication_1
